server:
  port: 8080
  address: 0.0.0.0

spring:
  application:
    name: stocktrades

  datasource:
    url: jdbc:h2:mem:StockInfo
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update